/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 astronaught.gltf 
Author: WA7KVI (https://sketchfab.com/WA7KVI)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astronaught-641b4b2e30fe4fc7898c5dee37b8598b
Title: Astronaught
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/astronaught/astronaught.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.03}>
        <mesh geometry={nodes.high_poly_default_0.geometry} material={materials['default']} rotation={[-Math.PI / 3, 0, 0]} scale={57.601} />
      </group>
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL + '/astronaught/astronaught.gltf')
