/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 coloredEarth.gltf 
Author: TheMillionPainter (https://sketchfab.com/TheMillionPainter)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/colorful-world-by-millionpainter-38b520cc255544e79e64baefbae74025
Title: Colorful World by Millionpainter
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF(process.env.PUBLIC_URL + '/coloredEarth/coloredEarth.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-69.597, 44.483, 67.596]} rotation={[-0.546, -0.698, 0.321]} scale={[2.971, 3.648, 2.971]}>
          <mesh geometry={nodes['Fl��che125_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che125_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-79.342, 40.342, 59.522]} rotation={[-0.491, -0.879, -0.527]} scale={[3.785, 4.647, 3.785]}>
          <mesh geometry={nodes['Fl��che126_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che126_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-75.711, 33.091, 68.367]} rotation={[-0.491, -0.879, 1.339]} scale={[3.412, 4.189, 3.412]}>
          <mesh geometry={nodes['Fl��che127_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che127_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-29.012, 27.146, 104.046]} rotation={[-0.197, -0.312, 1.511]} scale={[2.931, 3.599, 2.931]}>
          <mesh geometry={nodes['Fl��che128_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che128_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-32.207, 20.238, 104.371]} rotation={[-0.197, -0.312, 1.511]} scale={[2.341, 2.874, 2.341]}>
          <mesh geometry={nodes['Fl��che129_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che129_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-35.522, 13.239, 104.676]} rotation={[-0.197, -0.312, 1.511]} scale={[2.931, 3.599, 2.931]}>
          <mesh geometry={nodes['Fl��che130_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che130_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-48.848, 39.95, 92.22]} rotation={[-0.5, -0.426, 1.401]} scale={[2.564, 3.148, 2.564]}>
          <mesh geometry={nodes['Fl��che131_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che131_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-41.002, 25.329, 100.461]} rotation={[-0.02, -0.353, 0.731]} scale={[2.405, 2.953, 2.405]}>
          <mesh geometry={nodes['Fl��che132_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che132_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-69.357, -22.672, 84.383]} rotation={[0.213, -0.62, 0.224]} scale={[2.341, 2.874, 2.341]}>
          <mesh geometry={nodes['Fl��che133_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che133_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-63.515, -22.104, 88.769]} rotation={[0.213, -0.62, 0.224]} scale={[2.341, 2.874, 2.341]}>
          <mesh geometry={nodes['Fl��che134_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che134_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-57.936, -21.534, 92.962]} rotation={[0.213, -0.62, 0.224]} scale={[2.341, 2.874, 2.341]}>
          <mesh geometry={nodes['Fl��che135_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che135_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-53.714, -3.449, 103.201]} rotation={[0.082, -0.471, 2.995]} scale={[2.184, 2.681, 2.184]}>
          <mesh geometry={nodes['Fl��che136_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che136_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-8.629, 49.563, 93.939]} rotation={[-0.457, -0.136, 1.453]} scale={[3.411, 4.188, 3.411]}>
          <mesh geometry={nodes['Fl��che140_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che140_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[55.804, 40.731, 81.064]} rotation={[-0.428, 0.57, 1.446]} scale={[3.411, 4.188, 3.411]}>
          <mesh geometry={nodes['Fl��che141_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che141_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[54.394, 32.554, 85.787]} rotation={[-0.428, 0.57, 1.446]} scale={[3.411, 4.188, 3.411]}>
          <mesh geometry={nodes['Fl��che142_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che142_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[74.18, -14.082, 75.169]} rotation={[0.105, 0.783, 0.979]} scale={[3.411, 4.188, 3.411]}>
          <mesh geometry={nodes['Fl��che143_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che143_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[77.938, -6.668, 72.189]} rotation={[0.105, 0.783, 0.979]} scale={[2.895, 3.555, 2.895]}>
          <mesh geometry={nodes['Fl��che144_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che144_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[89.901, 11.28, 65.043]} rotation={[-0.321, 0.918, 1.302]} scale={[2.596, 3.187, 2.596]}>
          <mesh geometry={nodes['Fl��che145_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che145_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[95.055, 7.1, 57.899]} rotation={[-0.216, 1.086, 1.213]} scale={[3.004, 3.689, 3.004]}>
          <mesh geometry={nodes['Fl��che146_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che146_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[71.334, 72.186, 45.73]} rotation={[-0.995, 0.646, 1.805]} scale={[3.004, 3.689, 3.004]}>
          <mesh geometry={nodes['Fl��che147_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che147_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[72.184, 66.851, 52.767]} rotation={[-0.995, 0.646, 1.805]} scale={[3.633, 4.461, 3.633]}>
          <mesh geometry={nodes['Fl��che148_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che148_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[104.76, 23.741, 29.978]} rotation={[-0.522, 1.207, 1.493]} scale={[4.005, 4.918, 4.005]}>
          <mesh geometry={nodes['Fl��che149_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che149_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[105.167, 16.442, 32.942]} rotation={[-0.522, 1.207, 1.493]} scale={[2.664, 3.272, 2.664]}>
          <mesh geometry={nodes['Fl��che150_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che150_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[105.022, 10.857, 36.595]} rotation={[-0.522, 1.207, 1.493]} scale={[2.664, 3.272, 2.664]}>
          <mesh geometry={nodes['Fl��che151_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che151_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[43.701, 72.148, 65.282]} rotation={[-0.767, 0.409, 1.607]} scale={[2.705, 3.322, 2.705]}>
          <mesh geometry={nodes['Fl��che152_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che152_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[44.303, 65.709, 71.13]} rotation={[-0.767, 0.409, 1.607]} scale={[2.705, 3.322, 2.705]}>
          <mesh geometry={nodes['Fl��che153_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che153_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[48.376, 92.169, 22.838]} rotation={[-1.353, 0.546, 2.405]} scale={[3.018, 3.706, 3.018]}>
          <mesh geometry={nodes['Fl��che154_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che154_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[54.55, 90.349, 13.724]} rotation={[-1.353, 0.546, 2.405]} scale={[3.693, 4.535, 3.693]}>
          <mesh geometry={nodes['Fl��che155_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che155_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[56.749, 87.047, 22.452]} rotation={[-1.353, 0.546, 2.405]} scale={[3.018, 3.706, 3.018]}>
          <mesh geometry={nodes['Fl��che156_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che156_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[89.921, 20.532, -61.927]} rotation={[-2.83, 0.916, -2.994]} scale={[2.981, 3.66, 2.981]}>
          <mesh geometry={nodes['Fl��che163_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che163_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[84.459, 23.941, -68.304]} rotation={[-2.83, 0.916, -2.994]} scale={[3.615, 4.439, 3.615]}>
          <mesh geometry={nodes['Fl��che164_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che164_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[64.749, -21.352, -87.983]} rotation={[2.929, 0.613, -2.623]} scale={[4.081, 5.011, 4.081]}>
          <mesh geometry={nodes['Fl��che165_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che165_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[65.642, -9.522, -89.893]} rotation={[2.929, 0.613, -2.623]} scale={[2.458, 3.018, 2.458]}>
          <mesh geometry={nodes['Fl��che166_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che166_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[28.057, -35.735, -101.746]} rotation={[2.758, 0.297, -2.546]} scale={[2.974, 3.652, 2.974]}>
          <mesh geometry={nodes['Fl��che170_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che170_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[31.854, -44.303, -97.035]} rotation={[2.758, 0.297, -2.546]} scale={[3.533, 4.339, 3.533]}>
          <mesh geometry={nodes['Fl��che171_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che171_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-36.156, -18.979, -98.367]} rotation={[2.963, -0.313, -2.545]} scale={[3.709, 4.554, 3.709]}>
          <mesh geometry={nodes['Fl��che172_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che172_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-25.859, -18.462, -101.846]} rotation={[2.963, -0.313, -2.545]} scale={[2.937, 3.606, 2.937]}>
          <mesh geometry={nodes['Fl��che173_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che173_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-57.765, -34.024, -89.152]} rotation={[2.723, -0.571, 1.829]} scale={[2.877, 3.533, 2.877]}>
          <mesh geometry={nodes['Fl��che174_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che174_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-58.982, -42.071, -84.714]} rotation={[2.723, -0.571, 1.829]} scale={[3.487, 4.282, 3.487]}>
          <mesh geometry={nodes['Fl��che175_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che175_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-66.258, -35.066, -82.722]} rotation={[2.723, -0.571, 1.829]} scale={[3.03, 3.721, 3.03]}>
          <mesh geometry={nodes['Fl��che176_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che176_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-54.768, 67.472, -61.477]} rotation={[-2.305, -0.533, 3.109]} scale={[4.865, 5.974, 4.865]}>
          <mesh geometry={nodes['Fl��che177_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che177_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-67.076, 62.756, -54.639]} rotation={[-2.359, -0.664, 3.079]} scale={[4.865, 5.974, 4.865]}>
          <mesh geometry={nodes['Fl��che178_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che178_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-78.326, 55.714, -46.527]} rotation={[-2.212, -0.806, -3.105]} scale={[4.865, 5.974, 4.865]}>
          <mesh geometry={nodes['Fl��che179_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che179_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-64.322, 53.741, -66.638]} rotation={[-2.359, -0.664, 3.079]} scale={[3.466, 4.255, 3.466]}>
          <mesh geometry={nodes['Fl��che180_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che180_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-73.892, 48.822, -60.661]} rotation={[-2.589, -0.699, 2.934]} scale={[3.466, 4.255, 3.466]}>
          <mesh geometry={nodes['Fl��che181_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che181_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-108.787, 16.417, -17.371]} rotation={[-2.582, -1.392, 2.94]} scale={[3.466, 4.255, 3.466]}>
          <mesh geometry={nodes['Fl��che185_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che185_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-110.391, 8.188, -12.063]} rotation={[-2.582, -1.392, 2.94]} scale={[3.466, 4.255, 3.466]}>
          <mesh geometry={nodes['Fl��che186_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che186_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-108.88, 5.925, -23.338]} rotation={[-2.582, -1.392, 2.94]} scale={[2.633, 3.233, 2.633]}>
          <mesh geometry={nodes['Fl��che187_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che187_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-57.901, 5.693, 100.793]} rotation={[-0.109, -0.471, 2.908]} scale={[3.162, 3.882, 3.162]}>
          <mesh geometry={nodes['Fl��che188_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che188_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-49.064, 6.382, 105.243]} rotation={[-0.109, -0.471, 2.908]} scale={[3.643, 4.473, 3.643]}>
          <mesh geometry={nodes['Fl��che189_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che189_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-23.017, 8.797, 103.509]} rotation={[-0.1, -0.159, 1.534]} scale={[2.341, 2.874, 2.341]}>
          <mesh geometry={nodes['Fl��che190_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che190_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-24.943, 3.004, 103.781]} rotation={[-0.1, -0.159, 1.534]} scale={[2.341, 2.874, 2.341]}>
          <mesh geometry={nodes['Fl��che191_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che191_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[64.773, -59.089, 60.872]} rotation={[0.784, 0.662, 0.519]} scale={[3.411, 4.188, 3.411]}>
          <mesh geometry={nodes['Fl��che192_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che192_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[73.055, -56.227, 54.602]} rotation={[0.784, 0.662, 0.519]} scale={[4.537, 5.571, 4.537]}>
          <mesh geometry={nodes['Fl��che193_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che193_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[77.855, -59.279, 42.518]} rotation={[0.937, 0.808, 0.416]} scale={[3.987, 4.896, 3.987]}>
          <mesh geometry={nodes['Fl��che195_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che195_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[75.036, -88.73, 0.616]} rotation={[1.567, 0.653, 0.751]} scale={[3.987, 4.896, 3.987]}>
          <mesh geometry={nodes['Fl��che196_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che196_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[71.86, -91.187, -7.032]} rotation={[1.567, 0.653, 0.751]} scale={[3.188, 3.914, 3.188]}>
          <mesh geometry={nodes['Fl��che197_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che197_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-17.744, 105.232, -3.932]} rotation={[-1.574, -0.158, -2.911]} scale={[4.144, 5.089, 4.144]}>
          <mesh geometry={nodes['Fl��che200_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che200_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-8.817, 106.234, -9.14]} rotation={[-1.72, -0.051, -2.546]} scale={[4.144, 5.089, 4.144]}>
          <mesh geometry={nodes['Fl��che201_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che201_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-37.991, 94.694, -44.579]} rotation={[-2.067, -0.32, -2.049]} scale={[4.144, 5.089, 4.144]}>
          <mesh geometry={nodes['Fl��che202_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che202_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-37.517, 89.739, -54.063]} rotation={[-2.067, -0.32, -1.548]} scale={[4.699, 5.77, 4.699]}>
          <mesh geometry={nodes['Fl��che203_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che203_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-79.93, -9.944, 76.672]} rotation={[0.135, -0.777, 0.174]} scale={[4.707, 5.78, 4.707]}>
          <mesh geometry={nodes['Fl��che204_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che204_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-72.452, -5.8, 84.649]} rotation={[0.135, -0.777, 0.498]} scale={[3.615, 4.438, 3.615]}>
          <mesh geometry={nodes['Fl��che205_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che205_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-61.189, -96.55, 20.672]} rotation={[1.362, -0.541, 1.317]} scale={[4.658, 5.72, 4.658]}>
          <mesh geometry={nodes['Fl��che206_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che206_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-54.283, -91.551, 32.596]} rotation={[1.155, -0.515, 1.212]} scale={[3.249, 3.989, 3.249]}>
          <mesh geometry={nodes['Fl��che207_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che207_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-49.529, -91.203, 40.047]} rotation={[1.155, -0.515, 1.212]} scale={[2.896, 3.556, 2.896]}>
          <mesh geometry={nodes['Fl��che208_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che208_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-57.953, -86.104, 39.785]} rotation={[1.155, -0.515, 2.147]} scale={[3.726, 4.575, 3.726]}>
          <mesh geometry={nodes['Fl��che209_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che209_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[33.608, -101.069, -1.688]} rotation={[Math.PI / 2, 0.296, 0.75]} scale={[3.933, 4.83, 3.933]}>
          <mesh geometry={nodes['Fl��che210_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che210_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[39.37, -99.035, 7.065]} rotation={[1.402, 0.383, 0.806]} scale={[4.593, 5.639, 4.593]}>
          <mesh geometry={nodes['Fl��che211_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che211_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-52.387, -97.15, -15.224]} rotation={[1.783, -0.54, 3.06]} scale={[3.249, 3.989, 3.249]}>
          <mesh geometry={nodes['Fl��che214_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che214_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-59.992, -92.672, -14.382]} rotation={[1.783, -0.54, 3.06]} scale={[2.896, 3.556, 2.896]}>
          <mesh geometry={nodes['Fl��che215_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che215_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-57.186, -92.479, -23.272]} rotation={[1.783, -0.54, -2.288]} scale={[3.726, 4.575, 3.726]}>
          <mesh geometry={nodes['Fl��che216_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che216_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[93.395, 12.992, -48.942]} rotation={[-2.927, 1.087, -2.447]} scale={[3.734, 4.585, 3.734]}>
          <mesh geometry={nodes['Fl��che217_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che217_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[96.339, 6.564, -44.606]} rotation={[-2.927, 1.087, -2.447]} scale={[3.734, 4.585, 3.734]}>
          <mesh geometry={nodes['Fl��che218_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che218_Material007_0'].geometry} material={materials['Material.007']} />
        </group>
        <group position={[-38.47, 77.002, 58.561]} rotation={[-1.075, -0.316, 0.12]} scale={[6.203, 21.124, 21.124]}>
          <mesh geometry={nodes['Fl��che243_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che243_Material009_0'].geometry} material={materials['Material.009']} />
          <mesh geometry={nodes['Fl��che243_Material010_0'].geometry} material={materials['Material.010']} />
        </group>
        <group position={[-95.343, -50.148, -0.822]} rotation={[1.731, -0.971, 2.842]} scale={[5.075, 17.282, 17.282]}>
          <mesh geometry={nodes['Fl��che245_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che245_Material009_0'].geometry} material={materials['Material.009']} />
          <mesh geometry={nodes['Fl��che245_Material011_0'].geometry} material={materials['Material.011']} />
        </group>
        <group position={[-32.498, -74.087, 64.015]} rotation={[0.915, -0.29, -3.123]} scale={[6.582, 22.413, 22.413]}>
          <mesh geometry={nodes['Fl��che246_Material006_0'].geometry} material={materials['Material.006']} />
          <mesh geometry={nodes['Fl��che246_Material009_0'].geometry} material={materials['Material.009']} />
          <mesh geometry={nodes['Fl��che246_Material011_0'].geometry} material={materials['Material.011']} />
        </group>
        <mesh geometry={nodes.Icokugel_Material002_0.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Icokugel001_Material001_0.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} scale={104.571} />
        <mesh geometry={nodes['Fl��che005_Material005_0'].geometry} material={materials['Material.005']} position={[-36.445, 68.271, 73.335]} rotation={[-0.698, -0.397, 0.365]} scale={0.851} />
        <mesh geometry={nodes['Fl��che006_Material005_0'].geometry} material={materials['Material.005']} position={[-25.007, 67.372, 78.427]} rotation={[-0.759, -0.232, 0.346]} scale={0.853} />
        <mesh geometry={nodes['Fl��che007_Material005_0'].geometry} material={materials['Material.005']} position={[-32.711, 61.736, 80.856]} rotation={[-0.698, -0.397, 0.365]} scale={1.066} />
        <mesh geometry={nodes['Fl��che008_Material005_0'].geometry} material={materials['Material.005']} position={[-42.002, 59.76, 77.432]} rotation={[-0.698, -0.397, 0.365]} scale={1.066} />
        <mesh geometry={nodes['Fl��che009_Material005_0'].geometry} material={materials['Material.005']} position={[-42.501, 52.185, 88.818]} rotation={[-0.5, -0.426, 0.444]} scale={0.863} />
        <mesh geometry={nodes['Fl��che010_Material005_0'].geometry} material={materials['Material.005']} position={[-15.918, 53.931, 90.677]} rotation={[-0.457, -0.136, 0.456]} scale={0.967} />
        <mesh geometry={nodes['Fl��che011_Material005_0'].geometry} material={materials['Material.005']} position={[-13.854, 62.288, 85.193]} rotation={[-0.641, -0.106, 0.434]} scale={0.721} />
        <mesh geometry={nodes['Fl��che012_Material005_0'].geometry} material={materials['Material.005']} position={[-57.566, 50.436, 81.982]} rotation={[-0.5, -0.426, 0.471]} scale={0.739} />
        <mesh geometry={nodes['Fl��che013_Material005_0'].geometry} material={materials['Material.005']} position={[-50.574, 59.572, 72.902]} rotation={[-0.698, -0.397, 0.392]} scale={0.777} />
        <mesh geometry={nodes['Fl��che014_Material005_0'].geometry} material={materials['Material.005']} position={[-18.597, 45.097, 94.618]} rotation={[-0.457, -0.136, 0.456]} scale={1.066} />
        <mesh geometry={nodes['Fl��che015_Material005_0'].geometry} material={materials['Material.005']} position={[-30.845, 57.729, 91.805]} rotation={[-0.388, -0.296, 0.471]} scale={0.753} />
        <mesh geometry={nodes['Fl��che016_Material005_0'].geometry} material={materials['Material.005']} position={[-20.981, 62.484, 84.101]} rotation={[-0.641, -0.106, 0.42]} scale={0.759} />
        <mesh geometry={nodes['Fl��che017_Material005_0'].geometry} material={materials['Material.005']} position={[-34.1, 39.716, 98.086]} rotation={[-0.388, -0.296, 0.471]} scale={0.859} />
        <mesh geometry={nodes['Fl��che018_Material005_0'].geometry} material={materials['Material.005']} position={[-49.06, 46.029, 88.789]} rotation={[-0.5, -0.426, 0.431]} scale={0.897} />
        <mesh geometry={nodes['Fl��che019_Material005_0'].geometry} material={materials['Material.005']} position={[-25.253, 73.797, 72.253]} rotation={[-0.759, -0.232, 0.347]} scale={0.709} />
        <mesh geometry={nodes['Fl��che020_Material005_0'].geometry} material={materials['Material.005']} position={[-35.009, -20.715, 98.432]} rotation={[0.178, -0.313, 0.618]} scale={0.845} />
        <mesh geometry={nodes['Fl��che021_Material005_0'].geometry} material={materials['Material.005']} position={[-23.686, -20.428, 102.206]} rotation={[0.178, -0.313, 0.618]} scale={0.876} />
        <mesh geometry={nodes['Fl��che022_Material005_0'].geometry} material={materials['Material.005']} position={[-30.414, -10.138, 101.848]} rotation={[0.178, -0.313, 0.618]} scale={1.066} />
        <mesh geometry={nodes['Fl��che023_Material005_0'].geometry} material={materials['Material.005']} position={[-23.356, -11.889, 103.402]} rotation={[0.078, -0.16, 0.594]} scale={0.744} />
        <mesh geometry={nodes['Fl��che024_Material005_0'].geometry} material={materials['Material.005']} position={[-16.093, -15.097, 104.325]} rotation={[0.078, -0.16, 0.594]} scale={0.841} />
        <mesh geometry={nodes['Fl��che025_Material005_0'].geometry} material={materials['Material.005']} position={[-14.939, -3.618, 105.403]} rotation={[0.078, -0.16, 0.594]} scale={0.778} />
        <mesh geometry={nodes['Fl��che026_Material005_0'].geometry} material={materials['Material.005']} position={[-47.006, -3.707, 106.609]} rotation={[0.082, -0.471, 0.595]} scale={0.78} />
        <mesh geometry={nodes['Fl��che027_Material005_0'].geometry} material={materials['Material.005']} position={[-51.654, -9.456, 103.761]} rotation={[0.082, -0.471, 0.595]} scale={0.827} />
        <mesh geometry={nodes['Fl��che028_Material005_0'].geometry} material={materials['Material.005']} position={[-52.118, -16.721, 102.927]} rotation={[0.082, -0.471, 0.595]} scale={0.698} />
        <mesh geometry={nodes['Fl��che029_Material005_0'].geometry} material={materials['Material.005']} position={[-76.452, 17.915, 79.442]} rotation={[-0.112, -0.779, 0.48]} scale={0.819} />
        <mesh geometry={nodes['Fl��che030_Material005_0'].geometry} material={materials['Material.005']} position={[-75.338, 8.546, 81.603]} rotation={[-0.112, -0.779, 0.48]} scale={0.764} />
        <mesh geometry={nodes['Fl��che031_Material005_0'].geometry} material={materials['Material.005']} position={[-81.946, 8.637, 75.034]} rotation={[-0.112, -0.779, 0.48]} scale={0.611} />
        <mesh geometry={nodes['Fl��che032_Material005_0'].geometry} material={materials['Material.005']} position={[-113.509, 9.193, 24.181]} rotation={[-0.563, -1.392, 0.061]} scale={0.642} />
        <mesh geometry={nodes['Fl��che033_Material005_0'].geometry} material={materials['Material.005']} position={[-113.213, 18.317, 20.36]} rotation={[-0.563, -1.392, 0.061]} scale={0.742} />
        <mesh geometry={nodes['Fl��che034_Material005_0'].geometry} material={materials['Material.005']} position={[-115.609, 9.511, 10.232]} rotation={[-0.563, -1.392, 0.061]} scale={0.868} />
        <mesh geometry={nodes['Fl��che035_Material005_0'].geometry} material={materials['Material.005']} position={[-104.227, -5.401, 21.55]} rotation={[0.463, -1.399, 1.074]} scale={0.881} />
        <mesh geometry={nodes['Fl��che036_Material005_0'].geometry} material={materials['Material.005']} position={[-106.104, -4.118, 10.108]} rotation={[0.463, -1.399, 1.074]} scale={1.066} />
        <mesh geometry={nodes['Fl��che037_Material005_0'].geometry} material={materials['Material.005']} position={[-104.927, -18.104, 8.787]} rotation={[Math.PI / 2, -1.403, 2.169]} scale={0.779} />
        <mesh geometry={nodes['Fl��che038_Material005_0'].geometry} material={materials['Material.005']} position={[48.671, 93.426, 36.394]} rotation={[-1.144, 0.517, -0.408]} scale={0.883} />
        <mesh geometry={nodes['Fl��che039_Material005_0'].geometry} material={materials['Material.005']} position={[53.234, 88.412, 41.146]} rotation={[-1.144, 0.517, -0.408]} scale={1.066} />
        <mesh geometry={nodes['Fl��che040_Material005_0'].geometry} material={materials['Material.005']} position={[57.408, 89.082, 33.943]} rotation={[-1.144, 0.517, -0.408]} scale={0.856} />
        <mesh geometry={nodes['Fl��che041_Material005_0'].geometry} material={materials['Material.005']} position={[56.433, 82.808, 49.069]} rotation={[-1.144, 0.517, -0.408]} scale={0.781} />
        <mesh geometry={nodes['Fl��che042_Material005_0'].geometry} material={materials['Material.005']} position={[61.572, 82.812, 42.003]} rotation={[-1.144, 0.517, -0.408]} scale={1.066} />
        <mesh geometry={nodes['Fl��che043_Material005_0'].geometry} material={materials['Material.005']} position={[70.592, 80.688, 33.665]} rotation={[-0.995, 0.646, -0.49]} scale={0.743} />
        <mesh geometry={nodes['Fl��che044_Material005_0'].geometry} material={materials['Material.005']} position={[65.31, 77.387, 46.063]} rotation={[-0.995, 0.646, -0.49]} scale={0.869} />
        <mesh geometry={nodes['Fl��che045_Material005_0'].geometry} material={materials['Material.005']} position={[55.113, 77.443, 59.621]} rotation={[-0.795, 0.587, -0.607]} scale={0.735} />
        <mesh geometry={nodes['Fl��che046_Material005_0'].geometry} material={materials['Material.005']} position={[64.425, 72.336, 55.067]} rotation={[-0.995, 0.646, -0.49]} scale={0.81} />
        <mesh geometry={nodes['Fl��che047_Material005_0'].geometry} material={materials['Material.005']} position={[78.168, 75.093, 42.961]} rotation={[-1.043, 0.811, -0.458]} scale={0.814} />
        <mesh geometry={nodes['Fl��che048_Material005_0'].geometry} material={materials['Material.005']} position={[84.163, 28.159, 67.338]} rotation={[-0.321, 0.918, -1.019]} scale={0.699} />
        <mesh geometry={nodes['Fl��che049_Material005_0'].geometry} material={materials['Material.005']} position={[95.727, 26.709, 51.886]} rotation={[-0.321, 0.918, -1.019]} scale={0.816} />
        <mesh geometry={nodes['Fl��che050_Material005_0'].geometry} material={materials['Material.005']} position={[90.38, 18.497, 61.984]} rotation={[-0.321, 0.918, -1.019]} scale={1.066} />
        <mesh geometry={nodes['Fl��che051_Material005_0'].geometry} material={materials['Material.005']} position={[99.681, 16.177, 46.918]} rotation={[-0.216, 1.086, -1.108]} scale={0.737} />
        <mesh geometry={nodes['Fl��che052_Material005_0'].geometry} material={materials['Material.005']} position={[97.084, 10.577, 53.194]} rotation={[-0.216, 1.086, -1.108]} scale={0.841} />
        <mesh geometry={nodes['Fl��che053_Material005_0'].geometry} material={materials['Material.005']} position={[68.084, 26.41, 78.255]} rotation={[-0.215, 0.62, -1.108]} scale={0.744} />
        <mesh geometry={nodes['Fl��che054_Material005_0'].geometry} material={materials['Material.005']} position={[73.807, 18.274, 74.577]} rotation={[-0.137, 0.778, -1.159]} scale={0.756} />
        <mesh geometry={nodes['Fl��che055_Material005_0'].geometry} material={materials['Material.005']} position={[78.866, 7.793, 70.988]} rotation={[-0.137, 0.778, -1.159]} scale={0.937} />
        <mesh geometry={nodes['Fl��che056_Material005_0'].geometry} material={materials['Material.005']} position={[64.423, 17.304, 82.914]} rotation={[-0.215, 0.62, -1.108]} scale={0.777} />
        <mesh geometry={nodes['Fl��che057_Material005_0'].geometry} material={materials['Material.005']} position={[70.009, 8.361, 79.724]} rotation={[-0.137, 0.778, -1.159]} scale={0.745} />
        <mesh geometry={nodes['Fl��che058_Material005_0'].geometry} material={materials['Material.005']} position={[-73.655, 85.589, -29.313]} rotation={[-1.949, -0.612, -0.884]} scale={0.812} />
        <mesh geometry={nodes['Fl��che059_Material005_0'].geometry} material={materials['Material.005']} position={[-69.995, 84.144, -39.911]} rotation={[-1.949, -0.612, -0.884]} scale={0.844} />
        <mesh geometry={nodes['Fl��che060_Material005_0'].geometry} material={materials['Material.005']} position={[-65.629, 82.732, -50.22]} rotation={[-2.106, -0.486, -0.967]} scale={0.634} />
        <mesh geometry={nodes['Fl��che061_Material005_0'].geometry} material={materials['Material.005']} position={[-62.277, 88.661, -43.211]} rotation={[-1.949, -0.612, -0.884]} scale={0.968} />
        <mesh geometry={nodes['Fl��che062_Material005_0'].geometry} material={materials['Material.005']} position={[-64.587, 91.137, -32.583]} rotation={[-1.949, -0.612, -0.884]} scale={1.066} />
        <mesh geometry={nodes['Fl��che063_Material005_0'].geometry} material={materials['Material.005']} position={[-69.229, 91.586, -19.819]} rotation={[-1.762, -0.556, -0.781]} scale={0.716} />
        <mesh geometry={nodes['Fl��che064_Material005_0'].geometry} material={materials['Material.005']} position={[-57.14, 95.075, -36.824]} rotation={[-1.949, -0.612, -0.884]} scale={0.768} />
        <mesh geometry={nodes['Fl��che065_Material005_0'].geometry} material={materials['Material.005']} position={[-57.891, 85.891, -52.915]} rotation={[-2.106, -0.486, -0.967]} scale={0.723} />
        <mesh geometry={nodes['Fl��che066_Material005_0'].geometry} material={materials['Material.005']} position={[-59.924, 96.477, -24.963]} rotation={[-1.762, -0.556, -0.794]} scale={0.837} />
        <mesh geometry={nodes['Fl��che070_Material005_0'].geometry} material={materials['Material.005']} position={[-38.501, 99.542, -1.671]} rotation={[-1.574, -0.296, -0.687]} scale={0.771} />
        <mesh geometry={nodes['Fl��che071_Material005_0'].geometry} material={materials['Material.005']} position={[-27.34, 102.925, -6.891]} rotation={[-1.574, -0.296, -0.687]} scale={0.806} />
        <mesh geometry={nodes['Fl��che072_Material005_0'].geometry} material={materials['Material.005']} position={[59.078, 32.119, -95.61]} rotation={[-2.718, 0.571, -0.493]} scale={0.789} />
        <mesh geometry={nodes['Fl��che073_Material005_0'].geometry} material={materials['Material.005']} position={[66.962, 34.241, -89.095]} rotation={[-2.718, 0.571, -0.493]} scale={1.066} />
        <mesh geometry={nodes['Fl��che074_Material005_0'].geometry} material={materials['Material.005']} position={[60.42, 43.226, -89.662]} rotation={[-2.718, 0.571, -0.493]} scale={0.767} />
        <mesh geometry={nodes['Fl��che075_Material005_0'].geometry} material={materials['Material.005']} position={[69.682, 44.957, -82.156]} rotation={[-2.545, 0.686, -0.595]} scale={0.949} />
        <mesh geometry={nodes['Fl��che076_Material005_0'].geometry} material={materials['Material.005']} position={[63.752, 53.327, -82.341]} rotation={[-2.545, 0.686, -0.595]} scale={0.669} />
        <mesh geometry={nodes['Fl��che077_Material005_0'].geometry} material={materials['Material.005']} position={[49.791, -19.677, -92.23]} rotation={[3.032, 0.471, -0.195]} scale={0.833} />
        <mesh geometry={nodes['Fl��che078_Material005_0'].geometry} material={materials['Material.005']} position={[44.582, -6.611, -96.335]} rotation={[3.032, 0.471, -0.195]} scale={1.066} />
        <mesh geometry={nodes['Fl��che079_Material005_0'].geometry} material={materials['Material.005']} position={[80.366, 39.263, -66.296]} rotation={[-2.561, 0.851, -0.637]} scale={0.83} />
        <mesh geometry={nodes['Fl��che080_Material005_0'].geometry} material={materials['Material.005']} position={[91.805, 32.931, -54.847]} rotation={[-2.561, 0.851, -0.637]} scale={0.648} />
        <mesh geometry={nodes['Fl��che081_Material005_0'].geometry} material={materials['Material.005']} position={[83.136, 46.688, -57.652]} rotation={[-2.561, 0.851, -0.637]} scale={0.872} />
        <mesh geometry={nodes['Fl��che082_Material005_0'].geometry} material={materials['Material.005']} position={[-51.707, 4.609, -92.882]} rotation={[-3.038, -0.47, -0.521]} scale={1.066} />
        <mesh geometry={nodes['Fl��che083_Material005_0'].geometry} material={materials['Material.005']} position={[-55.731, -6.363, -96.39]} rotation={[3.054, -0.47, -0.608]} scale={0.854} />
        <mesh geometry={nodes['Fl��che084_Material005_0'].geometry} material={materials['Material.005']} position={[-50.744, -15.721, -98.107]} rotation={[3.054, -0.47, -0.608]} scale={0.632} />
        <mesh geometry={nodes['Fl��che085_Material005_0'].geometry} material={materials['Material.005']} position={[-45.617, -4.867, -101.673]} rotation={[3.054, -0.47, -0.608]} scale={0.747} />
        <mesh geometry={nodes['Fl��che086_Material005_0'].geometry} material={materials['Material.005']} position={[-40.589, 6.209, -98.39]} rotation={[-3.038, -0.47, -0.521]} scale={0.692} />
        <mesh geometry={nodes['Fl��che087_Material005_0'].geometry} material={materials['Material.005']} position={[-46.458, 16.376, -94.334]} rotation={[-3.038, -0.47, -0.521]} scale={0.768} />
        <mesh geometry={nodes['Fl��che088_Material005_0'].geometry} material={materials['Material.005']} position={[-79.647, -21.666, -82.401]} rotation={[3.005, -0.775, -0.663]} scale={0.607} />
        <mesh geometry={nodes['Fl��che089_Material005_0'].geometry} material={materials['Material.005']} position={[-77.16, -10.084, -86.455]} rotation={[3.005, -0.775, -0.663]} scale={0.928} />
        <mesh geometry={nodes['Fl��che090_Material005_0'].geometry} material={materials['Material.005']} position={[-85.486, -9.233, -78.333]} rotation={[3.005, -0.775, -0.663]} scale={0.636} />
        <mesh geometry={nodes['Fl��che091_Material005_0'].geometry} material={materials['Material.005']} position={[-65.729, -15.792, -94.865]} rotation={[2.924, -0.62, -0.716]} scale={0.762} />
        <mesh geometry={nodes['Fl��che092_Material005_0'].geometry} material={materials['Material.005']} position={[-61.097, -24.936, -96.227]} rotation={[2.924, -0.62, -0.716]} scale={0.664} />
        <mesh geometry={nodes['Fl��che093_Material005_0'].geometry} material={materials['Material.005']} position={[57.873, 59.802, -66.463]} rotation={[-2.351, 0.586, -0.777]} scale={0.845} />
        <mesh geometry={nodes['Fl��che094_Material005_0'].geometry} material={materials['Material.005']} position={[66.908, 61.384, -56.34]} rotation={[-2.351, 0.586, -0.777]} scale={0.799} />
        <mesh geometry={nodes['Fl��che095_Material005_0'].geometry} material={materials['Material.005']} position={[57.631, 67.786, -58.618]} rotation={[-2.351, 0.586, -0.777]} scale={0.919} />
        <mesh geometry={nodes['Fl��che096_Material005_0'].geometry} material={materials['Material.005']} position={[90.419, -64.439, 10.26]} rotation={[1.334, 0.908, 1.595]} scale={0.796} />
        <mesh geometry={nodes['Fl��che097_Material005_0'].geometry} material={materials['Material.005']} position={[82.58, -72.902, 18.012]} rotation={[1.334, 0.908, 1.595]} scale={1.066} />
        <mesh geometry={nodes['Fl��che098_Material005_0'].geometry} material={materials['Material.005']} position={[88.419, -63.995, 23.032]} rotation={[1.334, 0.908, 1.595]} scale={0.699} />
        <mesh geometry={nodes['Fl��che099_Material005_0'].geometry} material={materials['Material.005']} position={[91.394, -72.104, 0.718]} rotation={[1.564, 0.833, 1.419]} scale={0.871} />
        <mesh geometry={nodes['Fl��che100_Material005_0'].geometry} material={materials['Material.005']} position={[83.044, -81.228, 8.508]} rotation={[1.564, 0.833, 1.419]} scale={0.844} />
        <mesh geometry={nodes['Fl��che101_Material005_0'].geometry} material={materials['Material.005']} position={[83.589, -80.722, -5.14]} rotation={[1.564, 0.833, 1.419]} scale={0.813} />
        <mesh geometry={nodes['Fl��che102_Material005_0'].geometry} material={materials['Material.005']} position={[86.282, -68.698, -15.248]} rotation={[1.809, 0.906, 1.232]} scale={0.75} />
        <mesh geometry={nodes['Fl��che103_Material005_0'].geometry} material={materials['Material.005']} position={[93.02, -60.973, -10.65]} rotation={[1.809, 0.906, 1.232]} scale={0.831} />
        <mesh geometry={nodes['Fl��che104_Material005_0'].geometry} material={materials['Material.005']} position={[57.018, -89.991, 33.611]} rotation={[1.191, 0.616, 1.669]} scale={0.847} />
        <mesh geometry={nodes['Fl��che105_Material005_0'].geometry} material={materials['Material.005']} position={[66.513, -84.415, 29.443]} rotation={[1.191, 0.616, 1.669]} scale={0.906} />
        <mesh geometry={nodes['Fl��che106_Material005_0'].geometry} material={materials['Material.005']} position={[63.529, -82.482, 39.99]} rotation={[1.191, 0.616, 1.669]} scale={0.761} />
        <mesh geometry={nodes['Fl��che107_Material005_0'].geometry} material={materials['Material.005']} position={[-65.339, -90.65, 3.932]} rotation={[1.453, -0.698, 2.06]} scale={0.799} />
        <mesh geometry={nodes['Fl��che108_Material005_0'].geometry} material={materials['Material.005']} position={[-69.796, -85.888, 12.382]} rotation={[1.453, -0.698, 2.06]} scale={1.066} />
        <mesh geometry={nodes['Fl��che109_Material005_0'].geometry} material={materials['Material.005']} position={[-76.303, -81.263, 4.996]} rotation={[1.453, -0.698, 2.06]} scale={0.877} />
        <mesh geometry={nodes['Fl��che110_Material005_0'].geometry} material={materials['Material.005']} position={[-72.947, -82.385, 19.511]} rotation={[1.453, -0.698, 2.06]} scale={0.855} />
        <mesh geometry={nodes['Fl��che111_Material005_0'].geometry} material={materials['Material.005']} position={[-47.409, -86.735, -39.017]} rotation={[1.989, -0.515, 2.372]} scale={1.066} />
        <mesh geometry={nodes['Fl��che112_Material005_0'].geometry} material={materials['Material.005']} position={[-48.823, -82.09, -47.5]} rotation={[1.989, -0.515, 2.372]} scale={0.772} />
        <mesh geometry={nodes['Fl��che113_Material005_0'].geometry} material={materials['Material.005']} position={[-57.98, -80.554, -38.201]} rotation={[1.989, -0.515, 2.372]} scale={0.92} />
        <mesh geometry={nodes['Fl��che114_Material005_0'].geometry} material={materials['Material.005']} position={[-32.548, -96.954, 31.444]} rotation={[1.213, -0.213, 2.079]} scale={0.862} />
        <mesh geometry={nodes['Fl��che115_Material005_0'].geometry} material={materials['Material.005']} position={[-37.92, -91.746, 38.706]} rotation={[1.095, -0.341, 2.047]} scale={0.83} />
        <mesh geometry={nodes['Fl��che116_Material005_0'].geometry} material={materials['Material.005']} position={[-24.723, -95.121, 41.166]} rotation={[1.213, -0.213, 2.079]} scale={0.944} />
        <mesh geometry={nodes['Fl��che117_Material005_0'].geometry} material={materials['Material.005']} position={[-38.904, -109.74, 6.661]} rotation={[1.469, -0.405, 2.158]} scale={0.75} />
        <mesh geometry={nodes['Fl��che118_Material005_0'].geometry} material={materials['Material.005']} position={[-50.126, -104.237, 13.175]} rotation={[1.469, -0.405, 2.158]} scale={0.889} />
        <mesh geometry={nodes['Fl��che119_Material005_0'].geometry} material={materials['Material.005']} position={[-44.498, -105.903, 20.612]} rotation={[1.469, -0.405, 2.158]} scale={0.803} />
        <mesh geometry={nodes['Fl��che120_Material005_0'].geometry} material={materials['Material.005']} position={[-44.874, 101.115, -13.548]} rotation={[-1.742, -0.38, -0.743]} scale={0.647} />
        <mesh geometry={nodes['Fl��che121_Material005_0'].geometry} material={materials['Material.005']} position={[-43.198, 99.651, -25.931]} rotation={[-1.742, -0.38, -0.743]} scale={0.678} />
        <mesh geometry={nodes['Fl��che122_Material005_0'].geometry} material={materials['Material.005']} position={[107.914, 35.414, 26.794]} rotation={[-0.9, 1.104, -0.522]} scale={0.596} />
        <mesh geometry={nodes['Fl��che123_Material005_0'].geometry} material={materials['Material.005']} position={[103.723, 43.785, 29.611]} rotation={[-0.9, 1.104, -0.522]} scale={0.816} />
        <mesh geometry={nodes['Fl��che124_Material005_0'].geometry} material={materials['Material.005']} position={[103.832, 37.235, 37.519]} rotation={[-0.9, 1.104, -0.522]} scale={0.623} />
        <mesh geometry={nodes['Fl��che137_Material005_0'].geometry} material={materials['Material.005']} position={[-54.053, -31.928, 86.264]} rotation={[0.422, -0.569, 0.766]} scale={0.587} />
        <mesh geometry={nodes['Fl��che138_Material005_0'].geometry} material={materials['Material.005']} position={[-60.731, -32.56, 81.302]} rotation={[0.422, -0.569, 0.766]} scale={0.567} />
        <mesh geometry={nodes['Fl��che139_Material005_0'].geometry} material={materials['Material.005']} position={[-55.767, -38.702, 82.024]} rotation={[0.422, -0.569, 0.766]} scale={0.517} />
        <mesh geometry={nodes['Fl��che157_Material005_0'].geometry} material={materials['Material.005']} position={[84.813, 60.786, 23.091]} rotation={[-1.305, 0.851, -0.277]} scale={0.569} />
        <mesh geometry={nodes['Fl��che158_Material005_0'].geometry} material={materials['Material.005']} position={[83.393, 63.984, 17.514]} rotation={[-1.305, 0.851, -0.277]} scale={0.643} />
        <mesh geometry={nodes['Fl��che159_Material005_0'].geometry} material={materials['Material.005']} position={[80.913, 68.746, 10.8]} rotation={[-1.305, 0.851, -0.277]} scale={0.554} />
        <mesh geometry={nodes['Fl��che160_Material005_0'].geometry} material={materials['Material.005']} position={[78.428, 68.669, 21.874]} rotation={[-1.305, 0.851, -0.277]} scale={0.554} />
        <mesh geometry={nodes['Fl��che161_Material005_0'].geometry} material={materials['Material.005']} position={[48.683, 59.732, 74.257]} rotation={[-0.767, 0.409, -0.62]} scale={0.485} />
        <mesh geometry={nodes['Fl��che162_Material005_0'].geometry} material={materials['Material.005']} position={[37.766, 70.496, 70.448]} rotation={[-0.767, 0.409, -0.62]} scale={0.485} />
        <mesh geometry={nodes['Fl��che167_Material005_0'].geometry} material={materials['Material.005']} position={[37.513, -11.818, -109.701]} rotation={[2.945, 0.312, -0.219]} scale={0.525} />
        <mesh geometry={nodes['Fl��che168_Material005_0'].geometry} material={materials['Material.005']} position={[33.676, -18.206, -109.689]} rotation={[2.945, 0.312, -0.219]} scale={0.525} />
        <mesh geometry={nodes['Fl��che169_Material005_0'].geometry} material={materials['Material.005']} position={[40.445, -17.815, -107.542]} rotation={[2.945, 0.312, -0.219]} scale={0.593} />
        <mesh geometry={nodes['Fl��che182_Material005_0'].geometry} material={materials['Material.005']} position={[-68.23, 45.064, -68.571]} rotation={[-2.589, -0.699, -1.283]} scale={0.587} />
        <mesh geometry={nodes['Fl��che183_Material005_0'].geometry} material={materials['Material.005']} position={[-74.104, 37.673, -67.328]} rotation={[-2.589, -0.699, -1.283]} scale={0.752} />
        <mesh geometry={nodes['Fl��che184_Material005_0'].geometry} material={materials['Material.005']} position={[-85.159, 49.332, -41.795]} rotation={[-2.367, -0.959, -1.118]} scale={0.752} />
        <mesh geometry={nodes['Fl��che194__0'].geometry} material={materials['Flche.194__0']} position={[69.997, -64.265, 49.623]} rotation={[0.937, 0.808, 0.416]} scale={[3.44, 4.224, 3.44]} />
        <mesh geometry={nodes['Fl��che198_Material005_0'].geometry} material={materials['Material.005']} position={[41.263, -95.773, 21.623]} rotation={[1.402, 0.383, 1.568]} scale={0.657} />
        <mesh geometry={nodes['Fl��che199_Material005_0'].geometry} material={materials['Material.005']} position={[34.738, -99.283, 16.695]} rotation={[1.402, 0.383, 1.568]} scale={0.657} />
        <mesh geometry={nodes['Fl��che212_Material005_0'].geometry} material={materials['Material.005']} position={[30.757, 19.695, -100.024]} rotation={[-2.965, 0.313, -0.386]} scale={0.689} />
        <mesh geometry={nodes['Fl��che213_Material005_0'].geometry} material={materials['Material.005']} position={[36.307, 14.035, -99.21]} rotation={[-2.965, 0.313, -0.386]} scale={0.689} />
        <mesh geometry={nodes['Fl��che220_Material008_0'].geometry} material={materials['Material.008']} position={[-47.255, 89.222, 21.49]} rotation={[-1.387, -0.554, 0.543]} scale={0.403} />
        <mesh geometry={nodes['Fl��che221_Material008_0'].geometry} material={materials['Material.008']} position={[-53.489, 73.371, 49.156]} rotation={[-1.033, -0.486, 1.663]} scale={0.553} />
        <mesh geometry={nodes['Fl��che222_Material008_0'].geometry} material={materials['Material.008']} position={[-77.596, 18.348, -65.714]} rotation={[-2.856, -0.923, -1.371]} scale={0.403} />
        <mesh geometry={nodes['Fl��che223_Material008_0'].geometry} material={materials['Material.008']} position={[-93.917, -32.474, -27.535]} rotation={[2.238, -1.111, -3.068]} scale={0.474} />
        <mesh geometry={nodes['Fl��che224_Material008_0'].geometry} material={materials['Material.008']} position={[-31.862, -61.726, 76.677]} rotation={[0.631, -0.35, 1.822]} scale={0.57} />
        <mesh geometry={nodes['Fl��che225_Material008_0'].geometry} material={materials['Material.008']} position={[-12.325, -66.585, 77.848]} rotation={[0.693, -0.071, 1.835]} scale={0.37} />
        <mesh geometry={nodes['Fl��che226_Material008_0'].geometry} material={materials['Material.008']} position={[-9.57, -42.795, 93.658]} rotation={[0.414, -0.139, 1.805]} scale={0.37} />
        <mesh geometry={nodes['Fl��che227_Material008_0'].geometry} material={materials['Material.008']} position={[-77.065, -59.095, 34.379]} rotation={[Math.PI / 3, -0.813, 1.289]} scale={0.37} />
        <mesh geometry={nodes['Fl��che229_Material008_0'].geometry} material={materials['Material.008']} position={[84.454, -10.775, 58.5]} rotation={[0.286, 0.923, 1.651]} scale={0.37} />
        <mesh geometry={nodes['Fl��che230_Material008_0'].geometry} material={materials['Material.008']} position={[79.808, -22.116, 61.562]} rotation={[0.286, 0.923, 1.651]} scale={0.37} />
        <mesh geometry={nodes['Fl��che231_Material008_0'].geometry} material={materials['Material.008']} position={[100.443, 11.465, -20.299]} rotation={[-2.676, 1.395, -1.681]} scale={0.522} />
        <mesh geometry={nodes['Fl��che232_Material008_0'].geometry} material={materials['Material.008']} position={[63.302, -61.057, -54.414]} rotation={[2.363, 0.616, -0.715]} scale={0.536} />
        <mesh geometry={nodes['Fl��che233_Material008_0'].geometry} material={materials['Material.008']} position={[46.973, -63.455, -66.786]} rotation={[2.44, 0.396, -0.744]} scale={0.304} />
        <mesh geometry={nodes['Fl��che235_Material008_0'].geometry} material={materials['Material.008']} position={[-27.932, -64.518, -76.412]} rotation={[2.51, -0.35, -1.641]} scale={0.406} />
        <mesh geometry={nodes['Fl��che237_Material008_0'].geometry} material={materials['Material.008']} position={[-25.998, 40.299, -91.061]} rotation={[-2.755, -0.292, -1.367]} scale={0.406} />
        <mesh geometry={nodes['Fl��che238_Material008_0'].geometry} material={materials['Material.008']} position={[1.621, -102.724, -11.784]} rotation={[1.72, 0.048, -2.477]} scale={0.495} />
        <mesh geometry={nodes['Fl��che239_Material008_0'].geometry} material={materials['Material.008']} position={[-4.688, -103.52, 4.881]} rotation={[1.478, -0.126, -2.46]} scale={0.293} />
        <mesh geometry={nodes['Fl��che242_Material008_0'].geometry} material={materials['Material.008']} position={[14.383, 95.187, 37.258]} rotation={[-1.212, 0.209, 0.026]} scale={0.281} />
        <mesh geometry={nodes.Icokugel003_Material_0.geometry} material={materials.Material} rotation={[-0.34, 0.248, -0.649]} scale={13.412} />
        <mesh geometry={nodes.Icokugel002_Material_0.geometry} material={materials.Material} rotation={[0.725, -0.835, -1.878]} scale={11.684} />
        <mesh geometry={nodes.Icokugel004_Material_0.geometry} material={materials.Material} rotation={[2.656, 0.725, -0.9]} scale={[-16.056, 16.056, 16.056]} />
        <mesh geometry={nodes.Icokugel005_Material_0.geometry} material={materials.Material} rotation={[0.869, -1.235, 2.148]} scale={11.832} />
        <mesh geometry={nodes.Icokugel006_Material_0.geometry} material={materials.Material} rotation={[-0.188, -0.208, -2.299]} scale={10.851} />
        <mesh geometry={nodes['Fl��che004_Material005_0'].geometry} material={materials['Material.005']} position={[-59.611, 89.276, -0.161]} rotation={[-1.577, -0.65, -0.675]} scale={0.607} />
        <mesh geometry={nodes['Fl��che067_Material005_0'].geometry} material={materials['Material.005']} position={[-64.485, 85.613, 6.416]} rotation={[-1.577, -0.65, -0.675]} scale={0.668} />
        <mesh geometry={nodes['Fl��che068_Material005_0'].geometry} material={materials['Material.005']} position={[-66.772, 83.819, -3.452]} rotation={[-1.577, -0.65, -0.675]} scale={0.799} />
        <mesh geometry={nodes['Fl��che069_Material005_0'].geometry} material={materials['Material.005']} position={[-72.693, 79.396, 9.321]} rotation={[-1.577, -0.65, -0.675]} scale={0.575} />
        <mesh geometry={nodes['Fl��che248_Material005_0'].geometry} material={materials['Material.005']} position={[-86.947, 59.378, -22.956]} rotation={[-1.819, -0.906, -0.847]} scale={0.575} />
        <mesh geometry={nodes['Fl��che249_Material005_0'].geometry} material={materials['Material.005']} position={[-83.443, 65.34, -17.607]} rotation={[-1.819, -0.906, -0.847]} scale={0.646} />
        <mesh geometry={nodes.Easteregg_Easteregg_0.geometry} material={materials.Easteregg} rotation={[0, -Math.PI / 2, 0]} scale={33.761} />
      </group>
    </group>
  )
}

useGLTF.preload(process.env.PUBLIC_URL + '/coloredEarth/coloredEarth.gltf')
